### ISSUE TITLE
switch rollup.config.js to TypeScript

### ISSUE THREAD

**Issue by cadamsmith** [cadamsmith/svelte_starter_app#5]
idk if its even possible, but see if it is

**Comment by jimmywarting** [comment]
[You might not need TypeScript... (syntax)](https://jimmywarting.github.io/you-might-not-need-typescript/)

**Comment by cadamsmith** [comment]
> [You might not need TypeScript... (syntax)](https://jimmywarting.github.io/you-might-not-need-typescript/)

@jimmywarting eh I like TypeScript, and I don't mind the overhead and specific quirks it carries with it. If you're looking around for a specific Svelte app template without TypeScript, I'd refer you to the official one over here https://github.com/sveltejs/template or at some point I may make another repo with a vanilla JS version of my template.
